name: Super Linter Lite
description: Simple lint verification for repositories
runs:
  using: "composite"
  steps:
    - name: Run lint checks
      run: bash ${{ github.action_path }}/lint.sh
      shell: bash
